### ISSUE TITLE
Many questions

### ISSUE THREAD

**Issue by Pascal66** [santacruz123/ewa#1]
I'm new with go.
Wich git branch to use ?
If I use master one, I've "main file invalid"
Wich data can I use ?
Can I use it in "real time" with history data in sqlite or without history ?
In another word , how I can use ?
Thank you

**Comment by santacruz123** [comment]
It's too early... nothing works yet

**Comment by Pascal66** [comment]
Ok, understand.
I've asked because i've translated it in java for my android bot (I cant run go on it).
And saw in your test a file path := "/Users/andrewvorobyov/gdrive/MotiveWave" +
		"/OANDA/analysis/CFD/SPX500USD" +
		"/Primary Analysis.mwml" that I can use
